#!/bin/bash
set -e

a1=$1
a2=$2
a3=$3

usage() {
	echo "Usage:"
	echo "./webapp create name url"
	echo "./webapp remove name"
	
	exit
}

remove() {
	profile=$(find $HOME/.var/webapps -name "*.$a2")
	desktop_file=$(find $HOME/.local/share/applications/ -name "$a2.*")
	
	if [ -z $profile ] || [ -z $desktop_file ]; then
		echo "Webapp $a2 not found"
		exit
	fi
	
	rm -r $profile
	rm -r $desktop_file
	echo "Removed $a2 webapp"
	
	exit
}

create() {
	profile_name="$(echo $RANDOM | md5sum | head -c 8).$a2"
	dst="$HOME/.var/webapps/$profile_name"
	export exec="firefox --profile $dst $a3"
	export name=$a2

	mkdir -p "$dst"
	cp -r profile/* $dst/

	perl -p -e 's/%name%/$ENV{name}/g;s/%exec%/$ENV{exec}/g' desktop_template \
	>> $HOME/.local/share/applications/$a2.desktop
	
	exit
}


if [ -z $(command -v perl) ]; then
	echo "perl not found"
	exit
fi

if [ -z "$a1" ] || [ -z "$a2" ]; then
	usage
fi

if [ $a1 = "create" ]; then
	if [ -z "$a3" ]; then
		usage
	else
		create
	fi

elif [ $a1 = "remove" ]; then
	remove
	
else
	usage
fi
